var navClass = document.createElement("ul");
navClass.className = "navbar-nav";
var navitem1 = document.createElement("li");
navitem1.className = "nav-item";
var a1 = document.createElement("a");
a1.href = "index.html";
a1.innerText = "player";
var navitem2 = document.createElement("li");
navitem1.className = "nav-item";
var a2 = document.createElement("a");
a2.href = "page1.html";
a2.innerText = "playlist";
var navitem3 = document.createElement("li");
navitem3.className = "nav-item";
var a3 = document.createElement("a");
a3.href = "page2.html";
a3.innerText = "player";
navitem1.appendChild(a1);
navitem2.appendChild(a2);
navitem3.appendChild(a3);
navClass.append(navitem1, navitem2, navitem3);
document.body.appendChild(navClass);
